# Generated by Django 4.2.13 on 2024-06-08 16:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(default='default_room_name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.JSONField()),
                ('departure', models.CharField(default='default_departure', max_length=255)),
                ('destination', models.CharField(default='default_destination', max_length=255)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('chat_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('kakaopay_deeplink', models.CharField(max_length=255)),
                ('preferred_conditions', models.CharField(blank=True, max_length=255, null=True)),
                ('average_review_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
    ]
