# Generated by Django 4.2.13 on 2024-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='departure_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='departure_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='destination_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='destination_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
