# Generated by Django 4.2.13 on 2024-06-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_departure_lat_chatroom_departure_lng_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
